# Generated by Django 5.0.6 on 2024-05-11 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cant_max_alumnos', models.PositiveBigIntegerField(blank=True, default=1000, null=True, verbose_name='Cantidad máxima de alumnos')),
            ],
            options={
                'verbose_name': 'Nombre de la Tarjeta',
                'verbose_name_plural': 'Nombres de la Tarjeta',
            },
        ),
    ]
