# Generated by Django 5.0.6 on 2024-05-18 21:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarjetas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('tipo', models.CharField(blank=True, choices=[('débito', 'Débito'), ('crédito', 'Crédito'), (' ', ' ')], max_length=25, null=True)),
            ],
            options={
                'verbose_name': 'Tarjeta',
                'verbose_name_plural': 'Tarjetas',
            },
        ),
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fecha_ingreso', models.DateTimeField(default=django.utils.timezone.now)),
                ('rubro', models.CharField(choices=[('Vestimenta', 'Vestimenta'), ('Calzado', 'Calzado'), ('Gastronomía', 'Gastronomía'), ('Servicios', 'Servicios'), ('Infantiles', 'Infantiles'), ('Electrodomésticos', 'Electrodomésticos'), ('Tecnología', 'Tecnología'), ('Bienestar y Tiempo Libre', 'Bienestar y Tiempo Libre'), ('Viajes y Turismo', 'Viajes y Turismo')], max_length=50)),
                ('nombre_local', models.CharField(max_length=100)),
                ('web_local', models.URLField(blank=True, null=True)),
                ('porcentaje', models.PositiveIntegerField(blank=True, null=True)),
                ('tarjeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tarjetas.tarjetas')),
            ],
        ),
    ]
