# Generated by Django 5.0.6 on 2024-05-11 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarjetas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarjeta',
            options={'verbose_name': 'Tarjeta', 'verbose_name_plural': 'Tarjetas'},
        ),
        migrations.RemoveField(
            model_name='tarjeta',
            name='cant_max_alumnos',
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='tipo',
            field=models.CharField(choices=[('débito', 'Débito'), ('crédito', 'Crédito')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='nombre',
            field=models.CharField(max_length=25),
        ),
    ]
