# Generated by Django 5.0.6 on 2024-05-22 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarjetas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descuento',
            name='porcentaje',
            field=models.PositiveIntegerField(default=15),
            preserve_default=False,
        ),
    ]
