# Generated by Django 5.0.6 on 2024-05-12 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarjetas', '0002_alter_tarjeta_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tarjeta',
            new_name='Tarjetas',
        ),
    ]
