# Generated by Django 5.0.6 on 2024-05-17 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarjetas', '0003_rename_tarjeta_tarjetas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjetas',
            name='tipo',
            field=models.CharField(blank=True, choices=[('débito', 'Débito'), ('crédito', 'Crédito'), (' ', ' ')], max_length=25, null=True),
        ),
    ]
