# Generated by Django 5.0.6 on 2024-05-17 02:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarjetas', '0005_descuento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='descuento',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='descuento',
            name='fecha_inicio',
        ),
        migrations.AddField(
            model_name='descuento',
            name='fecha_ingreso',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='descuento',
            name='nombre_local',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='descuento',
            name='rubro',
            field=models.CharField(blank=True, choices=[('Vestimenta', 'Vestimenta'), ('Calzado', 'Calzado'), ('Gastronomía', 'Gastronomía'), ('Servicios', 'Servicios'), ('Infantiles', 'Infantiles'), ('Electrodomésticos', 'Electrodomésticos'), ('Tecnología', 'Tecnología'), ('Bienestar y Tiempo Libre', 'Bienestar y Tiempo Libre'), ('Viajes y Turismo', 'Viajes y Turismo')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='descuento',
            name='web_local',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='descuento',
            name='porcentaje',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='descuento',
            name='tarjeta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tarjetas.tarjetas'),
        ),
    ]
