# Generated by Django 5.0.6 on 2024-05-21 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_customuser_groups_customuser_user_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
    ]
