# Generated by Django 5.0.6 on 2024-05-18 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bancos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del Banco')),
                ('web', models.URLField(verbose_name='Sitio Web del Banco')),
                ('pais_origen', models.CharField(blank=True, max_length=50, null=True, verbose_name='País de Origen')),
                ('casa_central', models.CharField(blank=True, max_length=50, null=True, verbose_name='Casa Central')),
                ('mail_contacto', models.EmailField(blank=True, max_length=50, null=True, verbose_name='Email de Contacto')),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
            },
        ),
    ]
