# Generated by Django 5.0.6 on 2024-05-14 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bancos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bancos',
            name='casa_central',
            field=models.CharField(default='alg', max_length=50, verbose_name='Casa Central'),
        ),
        migrations.AddField(
            model_name='bancos',
            name='mail_contacto',
            field=models.EmailField(default='algo', max_length=50, verbose_name='Email de Contacto'),
        ),
        migrations.AddField(
            model_name='bancos',
            name='pais_origen',
            field=models.CharField(default='Uruguay', max_length=50, verbose_name='País de Origen'),
        ),
    ]
